# 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# 2. Load Dataset

In [237]:
customers=pd.read_csv(r"D:\project\Saas DA\Dataset\Raw Datset\dim_customers.csv")

In [238]:
customers

,customer_id,signup_date,country,industry,company_size,segment
0,CUST_2000,2025-09-15,NaN,Logistics,unknown,SMB
1,CUST_2001,2025-10-10,NaN,E-commerce,500+,Enterprise
2,CUST_2002,2025-03-19,NaN,Logistics,201-500,small business
3,CUST_2003,2025-11-30,usa,Finance,51-200,SMB
4,CUST_2004,2025-01-30,NaN,NaN,51-200,small business
...,...,...,...,...,...,...
1545,CUST_2354,2025-05-13,United States,E-commerce,11-50,small business
1546,CUST_2365,2025-08-05,NaN,NaN,1-10,small business
1547,CUST_2309,2025-09-06,UK,NaN,51-200,mid
1548,CUST_2736,2025-06-07,Canada,NaN,unknown,ENT
1549,CUST_2998,2025-02-12,NaN,NaN,201-500,Enterprise

In [239]:
plans=pd.read_csv(r"D:\project\Saas DA\Dataset\Raw Datset\dim_plans.csv")

In [240]:
plans

   plan_id   plan_name  monthly_price billing_cycle
0  p_basic       Basic           29.0       Monthly
1    p_pro         Pro           79.0       Monthly
2    p_ent  Enterprise          499.0        Annual

In [241]:
payments=pd.read_csv(r"D:\project\Saas DA\Dataset\Raw Datset\fact_payments.csv")

In [242]:
payments

,payment_id,subscription_id,payment_date,amount,payment_status,payment_method
0,PAY_500001,SUB_30000,2025-09-16,499.0,refunded,CREDIT_CARD
1,PAY_500002,SUB_30001,2025-10-13,79.0,paid,STRIPE
2,PAY_500003,SUB_30002,2025-03-24,499.0,failed,ACH
3,PAY_500004,SUB_30002,2025-04-23,499.0,failed,PAYPAL
4,PAY_500005,SUB_30002,2025-05-21,499.0,failed,CREDIT_CARD
...,...,...,...,...,...,...
3058,PAY_503059,SUB_31496,2025-08-22,499.0,failed,CREDIT_CARD
3059,PAY_503060,SUB_31496,2025-09-18,499.0,PAID,CREDIT_CARD
3060,PAY_503061,SUB_31497,2025-03-27,29.0,refunded,STRIPE
3061,PAY_503062,SUB_31498,2025-01-16,79.0,failed,STRIPE
3062,PAY_503063,SUB_31499,2025-02-11,499.0,refunded,ACH

In [8]:
subscriptions=pd.read_csv(r"D:\project\Saas DA\Dataset\SaaS raw Datset\fact_subscriptions.csv")

In [9]:
subscriptions

     subscription_id customer_id  plan_id  start_date    end_date       status
0          SUB_30000   CUST_2000    p_ent  2025-09-16         NaN          ACT
1          SUB_30001   CUST_2001   P_PRO   2025-10-10         NaN          ACT
2          SUB_30002   CUST_2002    p_ent  2025-03-21         NaN       active
3          SUB_30003   CUST_2003    p_ent  2025-12-02  2026-07-01     canceled
4          SUB_30004   CUST_2004    p_ent  2025-01-30         NaN       active
...              ...         ...      ...         ...         ...          ...
1495       SUB_31495   CUST_3495   P_PRO   2025-09-30         NaN          ACT
1496       SUB_31496   CUST_3496    p_ent  2025-07-20         NaN          ACT
1497       SUB_31497   CUST_3497  p_basic  2025-03-26  2025-11-11    cancelled
1498       SUB_31498   CUST_3498    p_pro  2025-01-15         NaN  active_plan
1499       SUB_31499   CUST_3499    p_ent  2025-02-09         NaN       active

[1500 rows x 6 columns]

In [243]:
usage=pd.read_csv(r"D:\project\Saas DA\Dataset\Raw Datset\fact_usage.csv")

In [244]:
usage

,usage_id,customer_id,event_date,feature_name,login_count,session_minutes
0,USG_700001,CUST_2000,2025-09-08,dashboard_view,8,114.76
1,USG_700002,CUST_2000,2025-05-11,export_csv,3,44.68
2,USG_700003,CUST_2000,2025-01-17,export_csv,3,76.59
3,USG_700004,CUST_2000,2025-03-10,export_csv,8,58.81
4,USG_700005,CUST_2000,2025-05-25,export_csv,3,35.41
...,...,...,...,...,...,...
24751,USG_724752,CUST_2999,2025-01-20,team_invite,1,70.09
24752,USG_724753,CUST_2999,2025-01-14,export_csv,5,73.85
24753,USG_724754,CUST_2999,2025-05-20,team_invite,5,31.07
24754,USG_724755,CUST_2999,2025-10-25,export_csv,-8,25.97
24755,USG_724756,CUST_2999,2025-01-10,billing_edit,3,95.06

In [245]:
support = pd.read_csv(r"D:\project\Saas DA\Dataset\Raw Datset\fact_support.csv")

In [246]:
support

,ticket_id,customer_id,ticket_date,priority,category,resolution_time,status
0,TCK_900001,CUST_2006,2025-02-17,HIGH,Login Issue,12,Closed
1,TCK_900002,CUST_2006,2025-07-17,LOW,API Down,41,resolved
2,TCK_900003,CUST_2007,2025-08-23,LOW,Login Issue,21,Closed
3,TCK_900004,CUST_2008,2025-11-10,MEDIUM,Login Issue,43,resolved
4,TCK_900005,CUST_2008,2025-07-22,MEDIUM,Feature Request,1,resolved
...,...,...,...,...,...,...,...
779,TCK_900780,CUST_3491,2025-07-02,MEDIUM,Feature Request,8,resolved
780,TCK_900781,CUST_3491,2025-03-02,HIGH,API Down,19,open
781,TCK_900782,CUST_3496,2025-04-09,MEDIUM,Feature Request,64,resolved
782,TCK_900783,CUST_3496,2025-08-07,LOW,Login Issue,60,Closed
783,TCK_900784,CUST_3496,2025-07-08,CRITICAL,API Down,65,resolved

# Customers Dataset

## Data Inspection

In [14]:
customers

,customer_id,signup_date,country,industry,company_size,segment
0,CUST_2000,2025-09-15,NaN,Logistics,unknown,SMB
1,CUST_2001,2025-10-10,NaN,E-commerce,500+,Enterprise
2,CUST_2002,2025-03-19,NaN,Logistics,201-500,small business
3,CUST_2003,2025-11-30,usa,Finance,51-200,SMB
4,CUST_2004,2025-01-30,NaN,NaN,51-200,small business
...,...,...,...,...,...,...
1545,CUST_2354,2025-05-13,United States,E-commerce,11-50,small business
1546,CUST_2365,2025-08-05,NaN,NaN,1-10,small business
1547,CUST_2309,2025-09-06,UK,NaN,51-200,mid
1548,CUST_2736,2025-06-07,Canada,NaN,unknown,ENT
1549,CUST_2998,2025-02-12,NaN,NaN,201-500,Enterprise

In [15]:
customers.head()

   customer_id signup_date country    industry company_size         segment
0    CUST_2000  2025-09-15     NaN   Logistics      unknown             SMB
1    CUST_2001  2025-10-10     NaN  E-commerce         500+      Enterprise
2    CUST_2002  2025-03-19     NaN   Logistics      201-500  small business
3   CUST_2003   2025-11-30     usa     Finance       51-200             SMB
4    CUST_2004  2025-01-30     NaN         NaN       51-200  small business

In [16]:
customers.tail()

,customer_id,signup_date,country,industry,company_size,segment
1545,CUST_2354,2025-05-13,United States,E-commerce,11-50,small business
1546,CUST_2365,2025-08-05,NaN,NaN,1-10,small business
1547,CUST_2309,2025-09-06,UK,NaN,51-200,mid
1548,CUST_2736,2025-06-07,Canada,NaN,unknown,ENT
1549,CUST_2998,2025-02-12,NaN,NaN,201-500,Enterprise

In [17]:
customers.sample(10)

,customer_id,signup_date,country,industry,company_size,segment
653,CUST_2653,2025-06-26,US,Logistics,1-10,SMB
29,CUST_2029,2025-11-23,US,Logistics,51-200,ENT
1520,CUST_3199,2025-11-05,usa,NaN,201-500,SMB
685,CUST_2685,2025-12-18,CA,E-commerce,11-50,SMB
725,CUST_2725,2025-01-20,united kingdom,SaaS,51-200,Enterprise
710,CUST_2710,2025-03-05,Canada,Logistics,500+,Mid-Market
1284,CUST_3284,2025-09-24,US,Healthcare,1-10,Enterprise
67,CUST_2067,2025-09-10,NaN,NaN,51-200,mid
989,CUST_2989,2025-11-24,NaN,E-commerce,500+,Mid-Market
966,CUST_2966,2025-02-06,United States,SaaS,51-200,Mid-Market

In [18]:
customers.shape

(1550, 6)

In [19]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1550 entries, 0 to 1549
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   1550 non-null   object
 1   signup_date   1550 non-null   object
 2   country       1202 non-null   object
 3   industry      1305 non-null   object
 4   company_size  1550 non-null   object
 5   segment       1550 non-null   object
dtypes: object(6)
memory usage: 72.8+ KB

In [20]:
customers.describe(include="all")

       customer_id signup_date country industry company_size     segment
count         1550        1550    1202     1305         1550        1550
unique        1500         364       7        5            6           6
top      CUST_2423  2025-11-23     usa  Finance         1-10  Mid-Market
freq             2          11     184      272          285         285

## Quality Check

In [21]:
customers.columns

Index(['customer_id', 'signup_date', 'country', 'industry', 'company_size',
       'segment'],
      dtype='object')

In [22]:
customers.isnull().sum()

customer_id       0
signup_date       0
country         348
industry        245
company_size      0
segment           0
dtype: int64

In [23]:
customers.duplicated().sum()

np.int64(50)

In [24]:
customers['customer_id'].duplicated().sum()

np.int64(50)

In [25]:
customers.nunique()

customer_id     1500
signup_date      364
country            7
industry           5
company_size       6
segment            6
dtype: int64

In [26]:
customers[customers.duplicated(subset="customer_id", keep=False)]

,customer_id,signup_date,country,industry,company_size,segment
51,CUST_2051,2025-03-17,UK,Finance,1-10,mid
70,CUST_2070,2025-07-08,usa,SaaS,201-500,Mid-Market
76,CUST_2076,2025-11-08,UK,Healthcare,11-50,Enterprise
220,CUST_2220,2025-06-13,US,NaN,51-200,small business
259,CUST_2259,2025-06-12,United States,Finance,1-10,ENT
309,CUST_2309,2025-09-06,UK,NaN,51-200,mid
339,CUST_2339,2025-11-23,united kingdom,NaN,1-10,ENT
354,CUST_2354,2025-05-13,United States,E-commerce,11-50,small business
365,CUST_2365,2025-08-05,NaN,NaN,1-10,small business
413,CUST_2413,2025-07-01,CA,NaN,unknown,SMB
422,CUST_2422,2025-10-01,NaN,SaaS,51-200,ENT
423,CUST_2423,2025-09-14,CA,E-commerce,1-10,Mid-Market
428,CUST_2428,2025-09-06,UK,Healthcare,500+,mid
432,CUST_2432,2025-04-07,US,Healthcare,201-500,small business
433,CUST_2433,2025-05-18,CA,Logistics,11-50,small business
439,CUST_2439,2025-04-20,NaN,E-commerce,500+,Mid-Market
451,CUST_2451,2025-10-18,Canada,Healthcare,51-200,Mid-Market
607,CUST_2607,2025-07-24,NaN,Logistics,unknown,Mid-Market
610,CUST_2610,2025-07-25,NaN,NaN,11-50,Mid-Market
712,CUST_2712,2025-10-16,UK,NaN,1-10,small business
736,CUST_2736,2025-06-07,Canada,NaN,unknown,ENT
741,CUST_2741,2025-06-28,CA,Logistics,unknown,Enterprise
861,CUST_2861,2025-01-04,US,Logistics,51-200,SMB
864,CUST_2864,2025-08-18,UK,E-commerce,51-200,mid
888,CUST_2888,2025-09-20,NaN,NaN,500+,Mid-Market
998,CUST_2998,2025-02-12,NaN,NaN,201-500,Enterprise
1041,CUST_3041,2025-02-06,UK,E-commerce,201-500,mid
1063,CUST_3063,2025-09-25,United States,NaN,201-500,small business
1080,CUST_3080,2025-04-14,NaN,NaN,201-500,mid
1085,CUST_3085,2025-03-21,NaN,Finance,500+,Mid-Market
1105,CUST_3105,2025-08-10,CA,Finance,51-200,small business
1116,CUST_3116,2025-03-11,United States,Finance,201-500,SMB
1128,CUST_3128,2025-09-09,UK,Healthcare,11-50,ENT
1190,CUST_3190,2025-05-19,Canada,E-commerce,1-10,SMB
1199,CUST_3199,2025-11-05,usa,NaN,201-500,SMB
1234,CUST_3234,2025-08-28,CA,E-commerce,1-10,Enterprise
1249,CUST_3249,2025-03-07,NaN,E-commerce,1-10,mid
1268,CUST_3268,2025-08-24,United States,Healthcare,unknown,ENT
1272,CUST_3272,2025-08-07,Canada,Logistics,unknown,small business
1281,CUST_3281,2025-08-13,US,Finance,500+,mid
1284,CUST_3284,2025-09-24,US,Healthcare,1-10,Enterprise
1336,CUST_3336,2025-10-07,NaN,Healthcare,1-10,Mid-Market
1368,CUST_3368,2025-12-21,usa,Finance,unknown,Enterprise
1382,CUST_3382,2025-07-26,usa,Finance,unknown,Enterprise
1391,CUST_3391,2025-05-02,usa,E-commerce,11-50,ENT
1419,CUST_3419,2025-07-18,United States,Finance,51-200,mid
1432,CUST_3432,2025-01-05,usa,NaN,unknown,small business
1452,CUST_3452,2025-07-21,CA,Healthcare,11-50,Mid-Market
1470,CUST_3470,2025-11-15,CA,SaaS,500+,mid
1491,CUST_3491,2025-06-02,UK,E-commerce,201-500,Mid-Market
1500,CUST_3116,2025-03-11,United States,Finance,201-500,SMB
1501,CUST_3368,2025-12-21,usa,Finance,unknown,Enterprise
1502,CUST_2422,2025-10-01,NaN,SaaS,51-200,ENT
1503,CUST_2413,2025-07-01,CA,NaN,unknown,SMB
1504,CUST_2451,2025-10-18,Canada,Healthcare,51-200,Mid-Market
1505,CUST_2861,2025-01-04,US,Logistics,51-200,SMB
1506,CUST_3063,2025-09-25,United States,NaN,201-500,small business
1507,CUST_2741,2025-06-28,CA,Logistics,unknown,Enterprise
1508,CUST_3272,2025-08-07,Canada,Logistics,unknown,small business
1509,CUST_2259,2025-06-12,United States,Finance,1-10,ENT
1510,CUST_2888,2025-09-20,NaN,NaN,500+,Mid-Market
1511,CUST_3432,2025-01-05,usa,NaN,unknown,small business
1512,CUST_2712,2025-10-16,UK,NaN,1-10,small business
1513,CUST_3382,2025-07-26,usa,Finance,unknown,Enterprise
1514,CUST_2070,2025-07-08,usa,SaaS,201-500,Mid-Market
1515,CUST_3268,2025-08-24,United States,Healthcare,unknown,ENT
1516,CUST_3491,2025-06-02,UK,E-commerce,201-500,Mid-Market
1517,CUST_2607,2025-07-24,NaN,Logistics,unknown,Mid-Market
1518,CUST_2433,2025-05-18,CA,Logistics,11-50,small business
1519,CUST_2051,2025-03-17,UK,Finance,1-10,mid
1520,CUST_3199,2025-11-05,usa,NaN,201-500,SMB
1521,CUST_3128,2025-09-09,UK,Healthcare,11-50,ENT
1522,CUST_3190,2025-05-19,Canada,E-commerce,1-10,SMB
1523,CUST_3249,2025-03-07,NaN,E-commerce,1-10,mid
1524,CUST_3419,2025-07-18,United States,Finance,51-200,mid
1525,CUST_2432,2025-04-07,US,Healthcare,201-500,small business
1526,CUST_3452,2025-07-21,CA,Healthcare,11-50,Mid-Market
1527,CUST_3470,2025-11-15,CA,SaaS,500+,mid
1528,CUST_3234,2025-08-28,CA,E-commerce,1-10,Enterprise
1529,CUST_3281,2025-08-13,US,Finance,500+,mid
1530,CUST_3085,2025-03-21,NaN,Finance,500+,Mid-Market
1531,CUST_2610,2025-07-25,NaN,NaN,11-50,Mid-Market
1532,CUST_3284,2025-09-24,US,Healthcare,1-10,Enterprise
1533,CUST_3041,2025-02-06,UK,E-commerce,201-500,mid
1534,CUST_2220,2025-06-13,US,NaN,51-200,small business
1535,CUST_2339,2025-11-23,united kingdom,NaN,1-10,ENT
1536,CUST_2423,2025-09-14,CA,E-commerce,1-10,Mid-Market
1537,CUST_2428,2025-09-06,UK,Healthcare,500+,mid
1538,CUST_3105,2025-08-10,CA,Finance,51-200,small business
1539,CUST_2076,2025-11-08,UK,Healthcare,11-50,Enterprise
1540,CUST_3391,2025-05-02,usa,E-commerce,11-50,ENT
1541,CUST_2439,2025-04-20,NaN,E-commerce,500+,Mid-Market
1542,CUST_3336,2025-10-07,NaN,Healthcare,1-10,Mid-Market
1543,CUST_2864,2025-08-18,UK,E-commerce,51-200,mid
1544,CUST_3080,2025-04-14,NaN,NaN,201-500,mid
1545,CUST_2354,2025-05-13,United States,E-commerce,11-50,small business
1546,CUST_2365,2025-08-05,NaN,NaN,1-10,small business
1547,CUST_2309,2025-09-06,UK,NaN,51-200,mid
1548,CUST_2736,2025-06-07,Canada,NaN,unknown,ENT
1549,CUST_2998,2025-02-12,NaN,NaN,201-500,Enterprise

In [27]:
customers["customer_id"].value_counts()[customers["customer_id"].value_counts() > 1]

customer_id
CUST_2423      2
CUST_2259      2
CUST_2070      2
CUST_2736      2
CUST_2712      2
CUST_3491      2
CUST_2413      2
CUST_3470      2
CUST_2610      2
CUST_2741      2
CUST_2076      2
CUST_2428      2
CUST_2451      2
CUST_2365      2
CUST_2439      2
CUST_2607      2
CUST_2432      2
CUST_2354      2
CUST_2339      2
 CUST_2433     2
CUST_2422      2
CUST_2220      2
CUST_2309      2
CUST_2861      2
CUST_2864      2
 CUST_2888     2
CUST_2998      2
CUST_3041      2
CUST_3063      2
CUST_3080      2
CUST_3085      2
CUST_3105      2
CUST_3116      2
CUST_3128      2
CUST_3190      2
CUST_3199      2
CUST_3234      2
CUST_3249      2
CUST_3268      2
CUST_3272      2
CUST_3281      2
CUST_3284      2
CUST_3336      2
CUST_3368      2
CUST_3382      2
CUST_3391      2
CUST_3419      2
CUST_3432      2
CUST_2051      2
CUST_3452      2
Name: count, dtype: int64

In [28]:
customers.dtypes

customer_id     object
signup_date     object
country         object
industry        object
company_size    object
segment         object
dtype: object

In [29]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1550 entries, 0 to 1549
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   1550 non-null   object
 1   signup_date   1550 non-null   object
 2   country       1202 non-null   object
 3   industry      1305 non-null   object
 4   company_size  1550 non-null   object
 5   segment       1550 non-null   object
dtypes: object(6)
memory usage: 72.8+ KB

In [30]:
customers['country'].unique()

array([nan, 'usa', 'Canada', 'united kingdom', 'CA', 'United States',
       'US', 'UK'], dtype=object)

In [31]:
customers['country'].value_counts(dropna=False)

country
NaN               348
usa               184
Canada            182
US                182
United States     174
CA                170
united kingdom    155
UK                155
Name: count, dtype: int64

In [32]:
customers['industry'].unique()

array(['Logistics', 'E-commerce', 'Finance', nan, 'SaaS', 'Healthcare'],
      dtype=object)

In [33]:
customers['industry'].value_counts(dropna=False)

industry
SaaS          272
Finance       272
E-commerce    270
Healthcare    263
NaN           245
Logistics     228
Name: count, dtype: int64

In [34]:
customers['segment'].unique()

array(['SMB', 'Enterprise', 'small business', 'ENT', 'Mid-Market', 'mid'],
      dtype=object)

In [35]:
customers['segment'].value_counts(dropna=False)

segment
Mid-Market        285
small business    265
mid               265
SMB               260
ENT               244
Enterprise        231
Name: count, dtype: int64

In [36]:
customers['signup_date'].min()

'2025-01-01'

In [37]:
customers['signup_date'].max()

'2025-12-31'

## Data Cleaning

In [38]:
customers.drop_duplicates(subset='customer_id',inplace=True)

In [39]:
customers.duplicated().sum()

np.int64(0)

In [40]:
customers.head(2)

  customer_id signup_date country    industry company_size     segment
0   CUST_2000  2025-09-15     NaN   Logistics      unknown         SMB
1   CUST_2001  2025-10-10     NaN  E-commerce         500+  Enterprise

In [41]:
customers['country'].isnull().sum()

np.int64(337)

In [42]:
customers['country']=customers['country'].fillna("Unknown")

In [43]:
customers['country'].isnull().sum()

np.int64(0)

In [44]:
customers["industry"].isnull().sum()

np.int64(231)

In [45]:
customers['industry']=customers['industry'].fillna("Unknown")

In [46]:
customers["industry"].isnull().sum()

np.int64(0)

In [47]:
customers.isnull().sum()

customer_id     0
signup_date     0
country         0
industry        0
company_size    0
segment         0
dtype: int64

In [48]:
customers['country']=customers['country'].replace(["usa","United States","US"],"USA")
customers['country']=customers['country'].replace("CA","Canada")
customers['country']=customers['country'].replace("united kingdom","UK")

In [49]:
customers['country'].value_counts()

country
USA        523
Canada     340
Unknown    337
UK         300
Name: count, dtype: int64

In [50]:
customers['industry'].value_counts()

industry
SaaS          269
Finance       263
E-commerce    260
Healthcare    254
Unknown       231
Logistics     223
Name: count, dtype: int64

In [51]:
customers['segment'].unique()

array(['SMB', 'Enterprise', 'small business', 'ENT', 'Mid-Market', 'mid'],
      dtype=object)

In [52]:
customers['segment']=customers['segment'].replace({"small business":"SMB","Enterprise":"ENT","Mid-Market":"MID","mid":"MID"})

In [53]:
customers['segment'].value_counts()

segment
MID    529
SMB    510
ENT    461
Name: count, dtype: int64

In [54]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   1500 non-null   object
 1   signup_date   1500 non-null   object
 2   country       1500 non-null   object
 3   industry      1500 non-null   object
 4   company_size  1500 non-null   object
 5   segment       1500 non-null   object
dtypes: object(6)
memory usage: 82.0+ KB

In [55]:
customers['signup_date']=pd.to_datetime(customers['signup_date'],errors='coerce')

In [56]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   1500 non-null   object
 1   signup_date   1500 non-null   datetime64[ns]
 2   country       1500 non-null   object
 3   industry      1500 non-null   object
 4   company_size  1500 non-null   object
 5   segment       1500 non-null   object
dtypes: datetime64[ns](1), object(5)
memory usage: 82.0+ KB

In [57]:
customers["company_size"].value_counts(dropna=False)

company_size
1-10       274
11-50      262
51-200     256
201-500    247
unknown    236
500+       225
Name: count, dtype: int64

In [58]:
customers.columns=customers.columns.str.title()

In [59]:
customers_clean=customers.copy()

In [60]:
customers_clean.to_csv("customers_clean.csv",index=False)

In [61]:
customers_clean

      Customer_Id Signup_Date  Country    Industry Company_Size Segment
0       CUST_2000  2025-09-15  Unknown   Logistics      unknown     SMB
1       CUST_2001  2025-10-10  Unknown  E-commerce         500+     ENT
2       CUST_2002  2025-03-19  Unknown   Logistics      201-500     SMB
3      CUST_2003   2025-11-30      USA     Finance       51-200     SMB
4       CUST_2004  2025-01-30  Unknown     Unknown       51-200     SMB
...           ...         ...      ...         ...          ...     ...
1495    CUST_3495  2025-09-30      USA        SaaS         500+     MID
1496    CUST_3496  2025-07-19      USA  Healthcare        11-50     ENT
1497    CUST_3497  2025-03-25   Canada        SaaS        11-50     SMB
1498   CUST_3498   2025-01-13       UK     Unknown       51-200     ENT
1499    CUST_3499  2025-02-09  Unknown  E-commerce         1-10     SMB

[1500 rows x 6 columns]

# 2. Plans Dataset

## Data Inspection

In [62]:
plans

   plan_id   plan_name  monthly_price billing_cycle
0  p_basic       Basic           29.0       Monthly
1    p_pro         Pro           79.0       Monthly
2    p_ent  Enterprise          499.0        Annual

In [63]:
plans.shape

(3, 4)

In [64]:
plans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   plan_id        3 non-null      object
 1   plan_name      3 non-null      object
 2   monthly_price  3 non-null      float64
 3   billing_cycle  3 non-null      object
dtypes: float64(1), object(3)
memory usage: 228.0+ bytes

In [65]:
plans.describe()

       monthly_price
count       3.000000
mean      202.333333
std       258.134332
min        29.000000
25%        54.000000
50%        79.000000
75%       289.000000
max       499.000000

## Data Qualitycheck

In [66]:
plans.columns

Index(['plan_id', 'plan_name', 'monthly_price', 'billing_cycle'], dtype='object')

In [67]:
plans.isnull().sum()

plan_id          0
plan_name        0
monthly_price    0
billing_cycle    0
dtype: int64

In [68]:
plans.duplicated().sum()

np.int64(0)

In [69]:
plans.columns=plans.columns.str.title()

In [70]:
plans

   Plan_Id   Plan_Name  Monthly_Price Billing_Cycle
0  p_basic       Basic           29.0       Monthly
1    p_pro         Pro           79.0       Monthly
2    p_ent  Enterprise          499.0        Annual

In [71]:
plans_clean=plans.copy()

In [72]:
plans_clean.to_csv('plans_clean.csv',index=False)

In [73]:
plans_clean

   Plan_Id   Plan_Name  Monthly_Price Billing_Cycle
0  p_basic       Basic           29.0       Monthly
1    p_pro         Pro           79.0       Monthly
2    p_ent  Enterprise          499.0        Annual

# 3. Subscriptions Dataset

## Data Inspection

In [74]:
subscriptions

     subscription_id customer_id  plan_id  start_date    end_date       status
0          SUB_30000   CUST_2000    p_ent  2025-09-16         NaN          ACT
1          SUB_30001   CUST_2001   P_PRO   2025-10-10         NaN          ACT
2          SUB_30002   CUST_2002    p_ent  2025-03-21         NaN       active
3          SUB_30003   CUST_2003    p_ent  2025-12-02  2026-07-01     canceled
4          SUB_30004   CUST_2004    p_ent  2025-01-30         NaN       active
...              ...         ...      ...         ...         ...          ...
1495       SUB_31495   CUST_3495   P_PRO   2025-09-30         NaN          ACT
1496       SUB_31496   CUST_3496    p_ent  2025-07-20         NaN          ACT
1497       SUB_31497   CUST_3497  p_basic  2025-03-26  2025-11-11    cancelled
1498       SUB_31498   CUST_3498    p_pro  2025-01-15         NaN  active_plan
1499       SUB_31499   CUST_3499    p_ent  2025-02-09         NaN       active

[1500 rows x 6 columns]

In [75]:
subscriptions.shape

(1500, 6)

In [76]:
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   subscription_id  1500 non-null   object
 1   customer_id      1500 non-null   object
 2   plan_id          1500 non-null   object
 3   start_date       1500 non-null   object
 4   end_date         457 non-null    object
 5   status           1500 non-null   object
dtypes: object(6)
memory usage: 70.4+ KB

In [77]:
subscriptions.describe(include='all')

,subscription_id,customer_id,plan_id,start_date,end_date,status
count,1500,1500,1500,1500,457,1500
unique,1500,1500,4,358,282,6
top,SUB_31499,CUST_3499,p_ent,2025-11-23,2025-10-21,active_plan
freq,1,1,394,12,7,378

In [78]:
subscriptions.head()

  subscription_id customer_id plan_id  start_date    end_date    status
0       SUB_30000   CUST_2000   p_ent  2025-09-16         NaN       ACT
1       SUB_30001   CUST_2001  P_PRO   2025-10-10         NaN       ACT
2       SUB_30002   CUST_2002   p_ent  2025-03-21         NaN    active
3       SUB_30003   CUST_2003   p_ent  2025-12-02  2026-07-01  canceled
4       SUB_30004   CUST_2004   p_ent  2025-01-30         NaN    active

In [79]:
subscriptions.tail()

     subscription_id customer_id  plan_id  start_date    end_date       status
1495       SUB_31495   CUST_3495   P_PRO   2025-09-30         NaN          ACT
1496       SUB_31496   CUST_3496    p_ent  2025-07-20         NaN          ACT
1497       SUB_31497   CUST_3497  p_basic  2025-03-26  2025-11-11    cancelled
1498       SUB_31498   CUST_3498    p_pro  2025-01-15         NaN  active_plan
1499       SUB_31499   CUST_3499    p_ent  2025-02-09         NaN       active

In [80]:
subscriptions.sample(10)

     subscription_id customer_id  plan_id  start_date    end_date       status
1468       SUB_31468   CUST_3468    p_ent  2025-10-19  2025-12-30      churned
762        SUB_30762   CUST_2762    p_pro  2025-04-15  2025-09-16    cancelled
300        SUB_30300   CUST_2300   P_PRO   2025-04-05         NaN  active_plan
164        SUB_30164   CUST_2164    p_ent  2025-03-14  2025-07-23    cancelled
246        SUB_30246   CUST_2246  p_basic  2025-02-17         NaN          ACT
647        SUB_30647   CUST_2647  p_basic  2025-09-23         NaN       active
1031       SUB_31031   CUST_3031    p_ent  2025-04-22         NaN       active
649        SUB_30649   CUST_2649   P_PRO   2025-10-08  2026-05-03     canceled
642        SUB_30642   CUST_2642   P_PRO   2025-06-20         NaN       active
1148       SUB_31148   CUST_3148    p_pro  2025-07-13         NaN       active

In [81]:
subscriptions.dtypes

subscription_id    object
customer_id        object
plan_id            object
start_date         object
end_date           object
status             object
dtype: object

In [82]:
subscriptions.columns

Index(['subscription_id', 'customer_id', 'plan_id', 'start_date', 'end_date',
       'status'],
      dtype='object')

## Data Qualitycheck

In [83]:
subscriptions.isnull().sum()

subscription_id       0
customer_id           0
plan_id               0
start_date            0
end_date           1043
status                0
dtype: int64

In [84]:
subscriptions.duplicated().sum()

np.int64(0)

In [85]:
subscriptions['subscription_id'].duplicated().sum()

np.int64(0)

In [86]:
customers.columns

Index(['Customer_Id', 'Signup_Date', 'Country', 'Industry', 'Company_Size',
       'Segment'],
      dtype='object')

In [87]:
subscriptions[~subscriptions['customer_id'].isin(customers['Customer_Id'])]

     subscription_id customer_id  plan_id  start_date    end_date       status
3          SUB_30003   CUST_2003    p_ent  2025-12-02  2026-07-01     canceled
28         SUB_30028   CUST_2028    p_pro  2025-12-19  2026-03-22     canceled
36         SUB_30036   CUST_2036    p_pro  2025-06-03  2025-07-03    cancelled
43         SUB_30043   CUST_2043    p_pro  2025-09-19         NaN       active
63         SUB_30063   CUST_2063  p_basic  2025-03-08         NaN  active_plan
...              ...         ...      ...         ...         ...          ...
1457       SUB_31457   CUST_3457    p_ent  2025-05-07  2025-11-17      churned
1467       SUB_31467   CUST_3467    p_ent  2025-02-22  2025-07-29    cancelled
1486       SUB_31486   CUST_3486    p_ent  2025-08-09         NaN  active_plan
1493       SUB_31493   CUST_3493   P_PRO   2025-05-04         NaN          ACT
1498       SUB_31498   CUST_3498    p_pro  2025-01-15         NaN  active_plan

[121 rows x 6 columns]

In [88]:
len(subscriptions[~subscriptions['customer_id'].isin(customers['Customer_Id'])])

121

In [89]:
subscriptions['plan_id'].value_counts(dropna=False)

plan_id
p_ent      394
p_pro      390
P_PRO      359
p_basic    357
Name: count, dtype: int64

In [90]:
subscriptions['plan_id'].unique()

array(['p_ent', 'P_PRO ', 'p_pro', 'p_basic'], dtype=object)

In [91]:
subscriptions['status'].value_counts(dropna=False)

status
active_plan    378
ACT            333
active         332
canceled       166
churned        151
cancelled      140
Name: count, dtype: int64

In [92]:
subscriptions['status'].unique()

array(['ACT', 'active', 'canceled', 'active_plan', 'cancelled', 'churned'],
      dtype=object)

In [93]:
subscriptions.sample(20)

     subscription_id customer_id  plan_id  start_date    end_date       status
25         SUB_30025   CUST_2025    p_pro  2025-02-17  2025-08-07     canceled
1148       SUB_31148   CUST_3148    p_pro  2025-07-13         NaN       active
857        SUB_30857   CUST_2857  p_basic  2025-08-30         NaN  active_plan
1346       SUB_31346   CUST_3346   P_PRO   2025-04-07  2025-09-13     canceled
652        SUB_30652   CUST_2652    p_pro  2025-08-21         NaN  active_plan
214        SUB_30214   CUST_2214    p_ent  2025-03-22         NaN       active
140        SUB_30140   CUST_2140  p_basic  2025-04-28         NaN       active
1351       SUB_31351   CUST_3351  p_basic  2025-04-16  2025-04-07    cancelled
618        SUB_30618   CUST_2618    p_ent  2025-08-19         NaN          ACT
97         SUB_30097   CUST_2097   P_PRO   2025-04-05         NaN  active_plan
261        SUB_30261   CUST_2261  p_basic  2025-09-07         NaN       active
1217       SUB_31217   CUST_3217  p_basic  2025-10-23         NaN  active_plan
359        SUB_30359   CUST_2359  p_basic  2025-10-15         NaN       active
923        SUB_30923   CUST_2923    p_ent  2025-01-05         NaN  active_plan
900        SUB_30900   CUST_2900    p_pro  2025-06-14         NaN          ACT
670        SUB_30670   CUST_2670   P_PRO   2025-09-08         NaN          ACT
1212       SUB_31212   CUST_3212  p_basic  2025-02-18         NaN  active_plan
1227       SUB_31227   CUST_3227  p_basic  2025-08-06         NaN          ACT
377        SUB_30377   CUST_2377  p_basic  2025-12-24         NaN  active_plan
745        SUB_30745   CUST_2745    p_ent  2025-12-29         NaN  active_plan


## Data Cleanin

In [94]:
subscriptions=subscriptions[subscriptions['customer_id'].isin(customers['Customer_Id'])].copy()

In [95]:
subscriptions[~subscriptions['customer_id'].isin(customers['Customer_Id'])]

Empty DataFrame
Columns: [subscription_id, customer_id, plan_id, start_date, end_date, status]
Index: []

In [96]:
subscriptions[~subscriptions['customer_id'].isin(customers['Customer_Id'])]

Empty DataFrame
Columns: [subscription_id, customer_id, plan_id, start_date, end_date, status]
Index: []

In [97]:
subscriptions['plan_id']=subscriptions['plan_id'].str.strip()
subscriptions['plan_id']=subscriptions['plan_id'].str.lower()

In [98]:
subscriptions['plan_id'].sample(5)

956     p_basic
450       p_pro
691     p_basic
1476      p_ent
462       p_ent
Name: plan_id, dtype: object

In [99]:
subscriptions['status']=subscriptions['status'].replace(['ACT', 'active','active_plan'],"Active")

In [100]:
subscriptions['status']=subscriptions['status'].replace(['canceled','cancelled'],"cancelled")

In [101]:
subscriptions['status'].value_counts()

status
Active       965
cancelled    279
churned      135
Name: count, dtype: int64

In [102]:
subscriptions['status']=subscriptions['status'].str.title()

In [103]:
subscriptions[(subscriptions['status']=='Active') & (subscriptions['end_date'].notna())]

Empty DataFrame
Columns: [subscription_id, customer_id, plan_id, start_date, end_date, status]
Index: []

In [104]:
subscriptions[(subscriptions['status'].isin(['Cancelled','Churned'])) & (subscriptions['end_date'].isna())]

Empty DataFrame
Columns: [subscription_id, customer_id, plan_id, start_date, end_date, status]
Index: []

In [105]:
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1379 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   subscription_id  1379 non-null   object
 1   customer_id      1379 non-null   object
 2   plan_id          1379 non-null   object
 3   start_date       1379 non-null   object
 4   end_date         414 non-null    object
 5   status           1379 non-null   object
dtypes: object(6)
memory usage: 75.4+ KB

In [106]:
subscriptions['start_date']=pd.to_datetime(subscriptions['start_date'],errors='coerce')

In [107]:
subscriptions['end_date']=pd.to_datetime(subscriptions['end_date'],errors='coerce')

In [108]:
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1379 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   subscription_id  1379 non-null   object
 1   customer_id      1379 non-null   object
 2   plan_id          1379 non-null   object
 3   start_date       1379 non-null   datetime64[ns]
 4   end_date         414 non-null    datetime64[ns]
 5   status           1379 non-null   object
dtypes: datetime64[ns](2), object(4)
memory usage: 75.4+ KB

In [109]:
subscriptions['subscription_days']=(subscriptions['end_date']-subscriptions['start_date']).dt.days

In [110]:
subscriptions[subscriptions['subscription_days']<0]

,subscription_id,customer_id,plan_id,start_date,end_date,status,subscription_days
307,SUB_30307,CUST_2307,p_basic,2025-12-15,2025-12-01,Cancelled,-14.0
352,SUB_30352,CUST_2352,p_basic,2025-08-28,2025-08-09,Churned,-19.0
424,SUB_30424,CUST_2424,p_pro,2025-12-13,2025-12-03,Cancelled,-10.0
586,SUB_30586,CUST_2586,p_basic,2025-08-11,2025-07-28,Cancelled,-14.0
613,SUB_30613,CUST_2613,p_ent,2025-11-21,2025-11-05,Cancelled,-16.0
678,SUB_30678,CUST_2678,p_ent,2025-03-10,2025-02-25,Cancelled,-13.0
778,SUB_30778,CUST_2778,p_pro,2025-01-03,2024-12-16,Cancelled,-18.0
858,SUB_30858,CUST_2858,p_basic,2025-05-24,2025-05-15,Cancelled,-9.0
969,SUB_30969,CUST_2969,p_ent,2025-09-17,2025-09-07,Cancelled,-10.0
988,SUB_30988,CUST_2988,p_ent,2025-09-26,2025-09-14,Cancelled,-12.0
1114,SUB_31114,CUST_3114,p_pro,2025-02-17,2025-02-09,Cancelled,-8.0
1172,SUB_31172,CUST_3172,p_pro,2025-08-03,2025-07-18,Cancelled,-16.0
1267,SUB_31267,CUST_3267,p_pro,2025-12-08,2025-11-25,Churned,-13.0
1273,SUB_31273,CUST_3273,p_pro,2025-04-24,2025-04-16,Churned,-8.0
1322,SUB_31322,CUST_3322,p_pro,2025-10-15,2025-09-25,Cancelled,-20.0
1340,SUB_31340,CUST_3340,p_pro,2025-01-10,2024-12-26,Churned,-15.0
1351,SUB_31351,CUST_3351,p_basic,2025-04-16,2025-04-07,Cancelled,-9.0
1353,SUB_31353,CUST_3353,p_pro,2025-04-28,2025-04-17,Cancelled,-11.0
1411,SUB_31411,CUST_3411,p_basic,2025-12-08,2025-11-25,Cancelled,-13.0
1414,SUB_31414,CUST_3414,p_pro,2025-05-07,2025-04-27,Cancelled,-10.0
1476,SUB_31476,CUST_3476,p_ent,2025-03-01,2025-02-20,Churned,-9.0

In [111]:
(subscriptions['subscription_days']<0).sum()

np.int64(21)

In [112]:
subscriptions=subscriptions[(subscriptions['subscription_days']>=0) | (subscriptions['subscription_days'].isna())]

In [113]:
(subscriptions['subscription_days']<0).sum()

np.int64(0)

In [114]:
subscriptions

,subscription_id,customer_id,plan_id,start_date,end_date,status,subscription_days
0,SUB_30000,CUST_2000,p_ent,2025-09-16,NaT,Active,NaN
1,SUB_30001,CUST_2001,p_pro,2025-10-10,NaT,Active,NaN
2,SUB_30002,CUST_2002,p_ent,2025-03-21,NaT,Active,NaN
4,SUB_30004,CUST_2004,p_ent,2025-01-30,NaT,Active,NaN
5,SUB_30005,CUST_2005,p_pro,2025-04-28,NaT,Active,NaN
...,...,...,...,...,...,...,...
1494,SUB_31494,CUST_3494,p_pro,2025-01-25,2025-07-05,Churned,161.0
1495,SUB_31495,CUST_3495,p_pro,2025-09-30,NaT,Active,NaN
1496,SUB_31496,CUST_3496,p_ent,2025-07-20,NaT,Active,NaN
1497,SUB_31497,CUST_3497,p_basic,2025-03-26,2025-11-11,Cancelled,230.0
1499,SUB_31499,CUST_3499,p_ent,2025-02-09,NaT,Active,NaN

In [115]:
subscriptions["subscription_days"] = subscriptions["subscription_days"].fillna(0)

In [116]:
subscriptions["subscription_days"] = subscriptions["subscription_days"].astype(int)

In [117]:
subscriptions.columns=subscriptions.columns.str.title()

In [118]:
subscriptions

,Subscription_Id,Customer_Id,Plan_Id,Start_Date,End_Date,Status,Subscription_Days
0,SUB_30000,CUST_2000,p_ent,2025-09-16,NaT,Active,0
1,SUB_30001,CUST_2001,p_pro,2025-10-10,NaT,Active,0
2,SUB_30002,CUST_2002,p_ent,2025-03-21,NaT,Active,0
4,SUB_30004,CUST_2004,p_ent,2025-01-30,NaT,Active,0
5,SUB_30005,CUST_2005,p_pro,2025-04-28,NaT,Active,0
...,...,...,...,...,...,...,...
1494,SUB_31494,CUST_3494,p_pro,2025-01-25,2025-07-05,Churned,161
1495,SUB_31495,CUST_3495,p_pro,2025-09-30,NaT,Active,0
1496,SUB_31496,CUST_3496,p_ent,2025-07-20,NaT,Active,0
1497,SUB_31497,CUST_3497,p_basic,2025-03-26,2025-11-11,Cancelled,230
1499,SUB_31499,CUST_3499,p_ent,2025-02-09,NaT,Active,0

In [119]:
subscriptions_clean=subscriptions.copy()

In [120]:
subscriptions_clean

,Subscription_Id,Customer_Id,Plan_Id,Start_Date,End_Date,Status,Subscription_Days
0,SUB_30000,CUST_2000,p_ent,2025-09-16,NaT,Active,0
1,SUB_30001,CUST_2001,p_pro,2025-10-10,NaT,Active,0
2,SUB_30002,CUST_2002,p_ent,2025-03-21,NaT,Active,0
4,SUB_30004,CUST_2004,p_ent,2025-01-30,NaT,Active,0
5,SUB_30005,CUST_2005,p_pro,2025-04-28,NaT,Active,0
...,...,...,...,...,...,...,...
1494,SUB_31494,CUST_3494,p_pro,2025-01-25,2025-07-05,Churned,161
1495,SUB_31495,CUST_3495,p_pro,2025-09-30,NaT,Active,0
1496,SUB_31496,CUST_3496,p_ent,2025-07-20,NaT,Active,0
1497,SUB_31497,CUST_3497,p_basic,2025-03-26,2025-11-11,Cancelled,230
1499,SUB_31499,CUST_3499,p_ent,2025-02-09,NaT,Active,0

In [121]:
subscriptions_clean.to_csv('subscriptions_clean.csv',index=False,na_rep="")

# 4. Payments Dataset

## Data Inspection

In [122]:
payments

,payment_id,subscription_id,payment_date,amount,payment_status,payment_method
0,PAY_500001,SUB_30000,2025-09-16,499.0,refunded,CREDIT_CARD
1,PAY_500002,SUB_30001,2025-10-13,79.0,paid,STRIPE
2,PAY_500003,SUB_30002,2025-03-24,499.0,failed,ACH
3,PAY_500004,SUB_30002,2025-04-23,499.0,failed,PAYPAL
4,PAY_500005,SUB_30002,2025-05-21,499.0,failed,CREDIT_CARD
...,...,...,...,...,...,...
3058,PAY_503059,SUB_31496,2025-08-22,499.0,failed,CREDIT_CARD
3059,PAY_503060,SUB_31496,2025-09-18,499.0,PAID,CREDIT_CARD
3060,PAY_503061,SUB_31497,2025-03-27,29.0,refunded,STRIPE
3061,PAY_503062,SUB_31498,2025-01-16,79.0,failed,STRIPE
3062,PAY_503063,SUB_31499,2025-02-11,499.0,refunded,ACH

In [123]:
payments.shape

(3063, 6)

In [124]:
payments.columns

Index(['payment_id', 'subscription_id', 'payment_date', 'amount',
       'payment_status', 'payment_method'],
      dtype='object')

In [125]:
payments.head()

,payment_id,subscription_id,payment_date,amount,payment_status,payment_method
0,PAY_500001,SUB_30000,2025-09-16,499.0,refunded,CREDIT_CARD
1,PAY_500002,SUB_30001,2025-10-13,79.0,paid,STRIPE
2,PAY_500003,SUB_30002,2025-03-24,499.0,failed,ACH
3,PAY_500004,SUB_30002,2025-04-23,499.0,failed,PAYPAL
4,PAY_500005,SUB_30002,2025-05-21,499.0,failed,CREDIT_CARD

In [126]:
payments.tail()

,payment_id,subscription_id,payment_date,amount,payment_status,payment_method
3058,PAY_503059,SUB_31496,2025-08-22,499.0,failed,CREDIT_CARD
3059,PAY_503060,SUB_31496,2025-09-18,499.0,PAID,CREDIT_CARD
3060,PAY_503061,SUB_31497,2025-03-27,29.0,refunded,STRIPE
3061,PAY_503062,SUB_31498,2025-01-16,79.0,failed,STRIPE
3062,PAY_503063,SUB_31499,2025-02-11,499.0,refunded,ACH

In [127]:
payments.sample(5)

,payment_id,subscription_id,payment_date,amount,payment_status,payment_method
1758,PAY_501759,SUB_30883,2025-04-27,29.0,PAID,ACH
1441,PAY_501442,SUB_30725,2025-01-20,499.0,PAID,ACH
1651,PAY_501652,SUB_30829,2026-01-12,499.0,failed,CREDIT_CARD
3040,PAY_503041,SUB_31488,2025-05-12,499.0,refunded,PAYPAL
2870,PAY_502871,SUB_31397,2025-10-12,79.0,paid,CREDIT_CARD

In [128]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3063 entries, 0 to 3062
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   payment_id       3063 non-null   object
 1   subscription_id  3063 non-null   object
 2   payment_date     3063 non-null   object
 3   amount           3063 non-null   float64
 4   payment_status   3063 non-null   object
 5   payment_method   3063 non-null   object
dtypes: float64(1), object(5)
memory usage: 143.7+ KB

In [129]:
payments.describe(include='all')

,payment_id,subscription_id,payment_date,amount,payment_status,payment_method
count,3063,3063,3063,3063.000000,3063,3063
unique,3063,1500,442,NaN,4,4
top,PAY_503063,SUB_30009,2025-08-13,NaN,paid,PAYPAL
freq,1,4,19,NaN,788,804
mean,NaN,NaN,NaN,170.734900,NaN,NaN
std,NaN,NaN,NaN,199.738994,NaN,NaN
min,NaN,NaN,NaN,-499.000000,NaN,NaN
25%,NaN,NaN,NaN,29.000000,NaN,NaN
50%,NaN,NaN,NaN,79.000000,NaN,NaN
75%,NaN,NaN,NaN,499.000000,NaN,NaN
max,NaN,NaN,NaN,499.000000,NaN,NaN

## Data Qualitycheck

In [130]:
payments.columns

Index(['payment_id', 'subscription_id', 'payment_date', 'amount',
       'payment_status', 'payment_method'],
      dtype='object')

In [131]:
payments.isnull().sum()

payment_id         0
subscription_id    0
payment_date       0
amount             0
payment_status     0
payment_method     0
dtype: int64

In [132]:
payments.duplicated().sum()

np.int64(0)

In [133]:
payments["payment_id"].duplicated().sum()

np.int64(0)

In [134]:
payments = payments[payments["subscription_id"].isin(subscriptions["Subscription_Id"])]

In [135]:
payments[~payments['subscription_id'].isin(subscriptions['Subscription_Id'])]

Empty DataFrame
Columns: [payment_id, subscription_id, payment_date, amount, payment_status, payment_method]
Index: []

In [136]:
payments.dtypes

payment_id          object
subscription_id     object
payment_date        object
amount             float64
payment_status      object
payment_method      object
dtype: object

## Data Cleaning

In [137]:
payments['payment_status'].value_counts(dropna=False)

payment_status
paid        716
failed      706
PAID        704
refunded    687
Name: count, dtype: int64

In [138]:
payments['payment_status']=payments['payment_status'].replace(["paid","PAID"],"Paid")
payments['payment_status']=payments['payment_status'].str.title()

C:\Users\Suji Prasanth\AppData\Local\Temp\ipykernel_18456\3905524005.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payments['payment_status']=payments['payment_status'].replace(["paid","PAID"],"Paid")
C:\Users\Suji Prasanth\AppData\Local\Temp\ipykernel_18456\3905524005.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payments['payment_status']=payments['payment_status'].str.title()

In [139]:
payments[payments['amount']<0]

,payment_id,subscription_id,payment_date,amount,payment_status,payment_method
115,PAY_500116,SUB_30056,2025-08-14,-499.0,Paid,CREDIT_CARD
188,PAY_500189,SUB_30089,2025-03-30,-79.0,Refunded,ACH
406,PAY_500407,SUB_30206,2025-02-07,-79.0,Failed,CREDIT_CARD
452,PAY_500453,SUB_30225,2025-11-05,-29.0,Paid,PAYPAL
501,PAY_500502,SUB_30248,2025-03-13,-29.0,Refunded,CREDIT_CARD
585,PAY_500586,SUB_30290,2025-05-04,-79.0,Failed,ACH
635,PAY_500636,SUB_30316,2025-11-30,-499.0,Refunded,STRIPE
638,PAY_500639,SUB_30318,2025-07-31,-79.0,Paid,CREDIT_CARD
708,PAY_500709,SUB_30349,2025-12-13,-29.0,Paid,PAYPAL
791,PAY_500792,SUB_30398,2025-04-29,-29.0,Paid,CREDIT_CARD
969,PAY_500970,SUB_30485,2025-07-12,-29.0,Paid,PAYPAL
983,PAY_500984,SUB_30491,2025-04-03,-499.0,Paid,STRIPE
989,PAY_500990,SUB_30494,2025-05-16,-79.0,Paid,PAYPAL
1079,PAY_501080,SUB_30541,2025-04-11,-79.0,Refunded,STRIPE
1094,PAY_501095,SUB_30549,2025-12-18,-29.0,Refunded,CREDIT_CARD
1111,PAY_501112,SUB_30557,2025-08-17,-79.0,Failed,CREDIT_CARD
1145,PAY_501146,SUB_30576,2025-07-11,-29.0,Paid,CREDIT_CARD
1192,PAY_501193,SUB_30595,2025-08-16,-79.0,Paid,PAYPAL
1314,PAY_501315,SUB_30659,2025-01-11,-499.0,Paid,STRIPE
1324,PAY_501325,SUB_30663,2025-10-19,-499.0,Paid,ACH
1433,PAY_501434,SUB_30720,2026-01-05,-29.0,Failed,PAYPAL
1550,PAY_501551,SUB_30777,2026-01-12,-79.0,Failed,PAYPAL
1561,PAY_501562,SUB_30784,2025-03-29,-499.0,Refunded,PAYPAL
1662,PAY_501663,SUB_30833,2025-05-12,-79.0,Paid,CREDIT_CARD
1761,PAY_501762,SUB_30884,2025-03-17,-499.0,Paid,STRIPE
1788,PAY_501789,SUB_30897,2026-01-04,-29.0,Failed,PAYPAL
1895,PAY_501896,SUB_30945,2025-01-31,-79.0,Paid,ACH
1917,PAY_501918,SUB_30957,2025-02-23,-29.0,Paid,STRIPE
1966,PAY_501967,SUB_30981,2025-05-10,-79.0,Paid,ACH
2003,PAY_502004,SUB_30997,2025-11-28,-79.0,Paid,ACH
2018,PAY_502019,SUB_31005,2025-10-28,-499.0,Paid,STRIPE
2156,PAY_502157,SUB_31067,2026-01-02,-79.0,Failed,ACH
2165,PAY_502166,SUB_31070,2025-11-09,-499.0,Failed,PAYPAL
2193,PAY_502194,SUB_31080,2025-05-17,-499.0,Failed,ACH
2240,PAY_502241,SUB_31101,2025-09-07,-79.0,Refunded,PAYPAL
2416,PAY_502417,SUB_31186,2025-05-03,-499.0,Refunded,PAYPAL
2431,PAY_502432,SUB_31191,2025-08-20,-79.0,Paid,PAYPAL
2541,PAY_502542,SUB_31240,2025-05-09,-79.0,Refunded,STRIPE
2565,PAY_502566,SUB_31251,2025-10-28,-29.0,Refunded,STRIPE
2619,PAY_502620,SUB_31282,2025-05-12,-499.0,Paid,PAYPAL
2671,PAY_502672,SUB_31304,2025-11-12,-499.0,Refunded,CREDIT_CARD
2692,PAY_502693,SUB_31313,2025-09-15,-29.0,Refunded,CREDIT_CARD
2846,PAY_502847,SUB_31388,2025-03-24,-79.0,Failed,PAYPAL
2863,PAY_502864,SUB_31395,2025-12-08,-499.0,Paid,CREDIT_CARD
2956,PAY_502957,SUB_31444,2025-01-22,-499.0,Paid,PAYPAL

In [140]:
(payments['amount']<0).sum()

np.int64(45)

In [141]:
payments.groupby("payment_status")["amount"].apply(lambda x: (x < 0).sum())

payment_status
Failed      10
Paid        23
Refunded    12
Name: amount, dtype: int64

In [142]:
payments['amount'].value_counts()

amount
 79.0     1365
 499.0     724
 29.0      679
-79.0       18
-499.0      15
-29.0       12
Name: count, dtype: int64

In [143]:
mask=((payments['amount'])<0 &( payments['payment_status'].isin(['Paid','Failed'])))
payments.loc[mask,'amount']=payments.loc[mask,'amount'].abs()

In [144]:
mask=payments['payment_status']=="Refunded"
payments.loc[mask,'amount']=-payments.loc[mask,'amount'].abs()

In [145]:
payments.sample(10)

,payment_id,subscription_id,payment_date,amount,payment_status,payment_method
1315,PAY_501316,SUB_30659,2025-02-11,499.0,Failed,CREDIT_CARD
2380,PAY_502381,SUB_31166,2025-04-15,79.0,Paid,PAYPAL
807,PAY_500808,SUB_30406,2025-01-13,-79.0,Refunded,STRIPE
572,PAY_500573,SUB_30283,2025-06-24,29.0,Paid,STRIPE
3037,PAY_503038,SUB_31485,2025-01-10,79.0,Paid,CREDIT_CARD
8,PAY_500009,SUB_30005,2025-05-28,79.0,Paid,PAYPAL
1790,PAY_501791,SUB_30897,2026-03-04,29.0,Paid,ACH
2336,PAY_502337,SUB_31148,2025-07-13,79.0,Paid,PAYPAL
2304,PAY_502305,SUB_31132,2025-06-17,79.0,Paid,PAYPAL
286,PAY_500287,SUB_30140,2025-05-28,29.0,Failed,ACH

In [146]:
payments[payments['amount']<0]

,payment_id,subscription_id,payment_date,amount,payment_status,payment_method
0,PAY_500001,SUB_30000,2025-09-16,-499.0,Refunded,CREDIT_CARD
16,PAY_500017,SUB_30008,2025-07-28,-499.0,Refunded,ACH
30,PAY_500031,SUB_30014,2025-04-24,-79.0,Refunded,STRIPE
35,PAY_500036,SUB_30015,2026-01-03,-499.0,Refunded,STRIPE
42,PAY_500043,SUB_30020,2025-11-15,-499.0,Refunded,ACH
...,...,...,...,...,...,...
3049,PAY_503050,SUB_31491,2025-06-06,-79.0,Refunded,CREDIT_CARD
3052,PAY_503053,SUB_31492,2025-07-27,-29.0,Refunded,CREDIT_CARD
3053,PAY_503054,SUB_31492,2025-08-27,-29.0,Refunded,STRIPE
3060,PAY_503061,SUB_31497,2025-03-27,-29.0,Refunded,STRIPE
3062,PAY_503063,SUB_31499,2025-02-11,-499.0,Refunded,ACH

In [147]:
(payments['amount']<0).sum()

np.int64(687)

In [148]:
payments.isnull().sum()

payment_id         0
subscription_id    0
payment_date       0
amount             0
payment_status     0
payment_method     0
dtype: int64

In [149]:
payments.duplicated().sum()

np.int64(0)

In [150]:
payments['payment_id'].isnull().sum()

np.int64(0)

In [151]:
payments['payment_id'].duplicated().sum()

np.int64(0)

In [152]:
payments['payment_date']=pd.to_datetime(payments['payment_date'])

C:\Users\Suji Prasanth\AppData\Local\Temp\ipykernel_18456\3871555744.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payments['payment_date']=pd.to_datetime(payments['payment_date'])

In [153]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2813 entries, 0 to 3062
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   payment_id       2813 non-null   object
 1   subscription_id  2813 non-null   object
 2   payment_date     2813 non-null   datetime64[ns]
 3   amount           2813 non-null   float64
 4   payment_status   2813 non-null   object
 5   payment_method   2813 non-null   object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 153.8+ KB

In [154]:
payments.dtypes

payment_id                 object
subscription_id            object
payment_date       datetime64[ns]
amount                    float64
payment_status             object
payment_method             object
dtype: object

In [155]:
payments.columns=payments.columns.str.title()

In [156]:
payments

,Payment_Id,Subscription_Id,Payment_Date,Amount,Payment_Status,Payment_Method
0,PAY_500001,SUB_30000,2025-09-16,-499.0,Refunded,CREDIT_CARD
1,PAY_500002,SUB_30001,2025-10-13,79.0,Paid,STRIPE
2,PAY_500003,SUB_30002,2025-03-24,499.0,Failed,ACH
3,PAY_500004,SUB_30002,2025-04-23,499.0,Failed,PAYPAL
4,PAY_500005,SUB_30002,2025-05-21,499.0,Failed,CREDIT_CARD
...,...,...,...,...,...,...
3057,PAY_503058,SUB_31496,2025-07-21,499.0,Paid,STRIPE
3058,PAY_503059,SUB_31496,2025-08-22,499.0,Failed,CREDIT_CARD
3059,PAY_503060,SUB_31496,2025-09-18,499.0,Paid,CREDIT_CARD
3060,PAY_503061,SUB_31497,2025-03-27,-29.0,Refunded,STRIPE
3062,PAY_503063,SUB_31499,2025-02-11,-499.0,Refunded,ACH

In [157]:
payments_clean=payments.copy()

In [158]:
payments_clean.to_csv('payments_clean.csv',index=False)

In [159]:
payments_clean

,Payment_Id,Subscription_Id,Payment_Date,Amount,Payment_Status,Payment_Method
0,PAY_500001,SUB_30000,2025-09-16,-499.0,Refunded,CREDIT_CARD
1,PAY_500002,SUB_30001,2025-10-13,79.0,Paid,STRIPE
2,PAY_500003,SUB_30002,2025-03-24,499.0,Failed,ACH
3,PAY_500004,SUB_30002,2025-04-23,499.0,Failed,PAYPAL
4,PAY_500005,SUB_30002,2025-05-21,499.0,Failed,CREDIT_CARD
...,...,...,...,...,...,...
3057,PAY_503058,SUB_31496,2025-07-21,499.0,Paid,STRIPE
3058,PAY_503059,SUB_31496,2025-08-22,499.0,Failed,CREDIT_CARD
3059,PAY_503060,SUB_31496,2025-09-18,499.0,Paid,CREDIT_CARD
3060,PAY_503061,SUB_31497,2025-03-27,-29.0,Refunded,STRIPE
3062,PAY_503063,SUB_31499,2025-02-11,-499.0,Refunded,ACH

# 5. Usage Dataset

## Date Inspection

In [160]:
usage

,usage_id,customer_id,event_date,feature_name,login_count,session_minutes
0,USG_700001,CUST_2000,2025-09-08,dashboard_view,8,114.76
1,USG_700002,CUST_2000,2025-05-11,export_csv,3,44.68
2,USG_700003,CUST_2000,2025-01-17,export_csv,3,76.59
3,USG_700004,CUST_2000,2025-03-10,export_csv,8,58.81
4,USG_700005,CUST_2000,2025-05-25,export_csv,3,35.41
...,...,...,...,...,...,...
24751,USG_724752,CUST_2999,2025-01-20,team_invite,1,70.09
24752,USG_724753,CUST_2999,2025-01-14,export_csv,5,73.85
24753,USG_724754,CUST_2999,2025-05-20,team_invite,5,31.07
24754,USG_724755,CUST_2999,2025-10-25,export_csv,-8,25.97
24755,USG_724756,CUST_2999,2025-01-10,billing_edit,3,95.06

In [161]:
usage.shape

(24756, 6)

In [162]:
usage.columns

Index(['usage_id', 'customer_id', 'event_date', 'feature_name', 'login_count',
       'session_minutes'],
      dtype='object')

In [163]:
usage.dtypes

usage_id            object
customer_id         object
event_date          object
feature_name        object
login_count          int64
session_minutes    float64
dtype: object

In [164]:
usage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24756 entries, 0 to 24755
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   usage_id         24756 non-null  object
 1   customer_id      24756 non-null  object
 2   event_date       24756 non-null  object
 3   feature_name     23814 non-null  object
 4   login_count      24756 non-null  int64
 5   session_minutes  24756 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ MB

In [165]:
usage.describe(include='all')

,usage_id,customer_id,event_date,feature_name,login_count,session_minutes
count,24756,24756,24756,23814,24756.000000,24756.000000
unique,24756,1000,351,5,NaN,NaN
top,USG_724756,CUST_2327,2025-03-16,dashboard_view,NaN,NaN
freq,1,40,94,4849,NaN,NaN
mean,NaN,NaN,NaN,NaN,4.212514,61.998778
std,NaN,NaN,NaN,NaN,2.793990,33.283118
min,NaN,NaN,NaN,NaN,-8.000000,5.000000
25%,NaN,NaN,NaN,NaN,2.000000,33.160000
50%,NaN,NaN,NaN,NaN,4.000000,61.710000
75%,NaN,NaN,NaN,NaN,6.000000,90.820000
max,NaN,NaN,NaN,NaN,8.000000,120.000000

In [166]:
usage.head()

,usage_id,customer_id,event_date,feature_name,login_count,session_minutes
0,USG_700001,CUST_2000,2025-09-08,dashboard_view,8,114.76
1,USG_700002,CUST_2000,2025-05-11,export_csv,3,44.68
2,USG_700003,CUST_2000,2025-01-17,export_csv,3,76.59
3,USG_700004,CUST_2000,2025-03-10,export_csv,8,58.81
4,USG_700005,CUST_2000,2025-05-25,export_csv,3,35.41

In [167]:
usage.tail()

,usage_id,customer_id,event_date,feature_name,login_count,session_minutes
24751,USG_724752,CUST_2999,2025-01-20,team_invite,1,70.09
24752,USG_724753,CUST_2999,2025-01-14,export_csv,5,73.85
24753,USG_724754,CUST_2999,2025-05-20,team_invite,5,31.07
24754,USG_724755,CUST_2999,2025-10-25,export_csv,-8,25.97
24755,USG_724756,CUST_2999,2025-01-10,billing_edit,3,95.06

In [168]:
usage.sample(10)

,usage_id,customer_id,event_date,feature_name,login_count,session_minutes
14889,USG_714890,CUST_2598,2025-11-26,team_invite,5,104.24
9989,USG_709990,CUST_2403,2025-10-24,team_invite,7,69.55
16749,USG_716750,CUST_2673,2025-04-04,dashboard_view,5,58.16
2260,USG_702261,CUST_2092,2025-10-24,billing_edit,6,49.70
12575,USG_712576,CUST_2504,2025-01-07,billing_edit,5,88.41
5101,USG_705102,CUST_2205,2025-02-12,api_post,4,66.58
13364,USG_713365,CUST_2536,2025-01-20,export_csv,4,70.99
4145,USG_704146,CUST_2169,2025-12-02,dashboard_view,1,95.01
15696,USG_715697,CUST_2629,2025-08-27,billing_edit,1,38.70
152,USG_700153,CUST_2006,2025-10-09,team_invite,7,53.16

## Data Qualitycheck

In [169]:
usage.isnull().sum()

usage_id             0
customer_id          0
event_date           0
feature_name       942
login_count          0
session_minutes      0
dtype: int64

In [170]:
usage.duplicated().sum()

np.int64(0)

In [171]:
usage['usage_id'].isnull().sum()

np.int64(0)

In [172]:
usage['customer_id'].isnull().sum()

np.int64(0)

In [173]:
usage[~usage['customer_id'].isin(customers['Customer_Id'])]

,usage_id,customer_id,event_date,feature_name,login_count,session_minutes
82,USG_700083,CUST_2003,2025-12-13,export_csv,7,98.33
83,USG_700084,CUST_2003,2025-08-26,export_csv,1,79.47
84,USG_700085,CUST_2003,2025-06-09,export_csv,2,61.47
85,USG_700086,CUST_2003,2025-05-02,team_invite,2,99.81
86,USG_700087,CUST_2003,2025-08-17,api_post,1,117.25
...,...,...,...,...,...,...
24397,USG_724398,CUST_2983,2025-05-23,billing_edit,5,10.51
24398,USG_724399,CUST_2983,2025-03-18,billing_edit,1,9.87
24399,USG_724400,CUST_2983,2025-02-13,team_invite,3,16.62
24400,USG_724401,CUST_2983,2025-11-30,team_invite,7,51.81
24401,USG_724402,CUST_2983,2025-04-08,export_csv,7,7.25

In [174]:
usage['feature_name'].value_counts(dropna=False)

feature_name
dashboard_view    4849
team_invite       4825
billing_edit      4724
export_csv        4717
api_post          4699
NaN                942
Name: count, dtype: int64

In [175]:
usage['feature_name'].isnull().sum()

np.int64(942)

In [176]:
usage['feature_name'].value_counts()

feature_name
dashboard_view    4849
team_invite       4825
billing_edit      4724
export_csv        4717
api_post          4699
Name: count, dtype: int64

In [177]:
usage[usage['login_count']<0]

,usage_id,customer_id,event_date,feature_name,login_count,session_minutes
8,USG_700009,CUST_2000,2025-07-01,team_invite,-2,50.67
49,USG_700050,CUST_2001,2025-07-21,billing_edit,-7,77.09
62,USG_700063,CUST_2002,2025-01-25,team_invite,-2,86.81
69,USG_700070,CUST_2002,2025-04-20,billing_edit,-5,58.65
81,USG_700082,CUST_2002,2025-09-15,export_csv,-7,78.46
...,...,...,...,...,...,...
24570,USG_724571,CUST_2992,2025-10-04,team_invite,-2,13.13
24584,USG_724585,CUST_2993,2025-12-05,api_post,-8,15.62
24652,USG_724653,CUST_2994,2025-10-22,dashboard_view,-3,101.41
24681,USG_724682,CUST_2997,2025-12-16,billing_edit,-5,78.62
24754,USG_724755,CUST_2999,2025-10-25,export_csv,-8,25.97

In [178]:
(usage['login_count']<0).sum()

np.int64(810)

In [179]:
usage[usage['session_minutes']<0]

Empty DataFrame
Columns: [usage_id, customer_id, event_date, feature_name, login_count, session_minutes]
Index: []

In [180]:
(usage['session_minutes']<0).sum()

np.int64(0)

## Data Cleaning

In [181]:
usage = usage[usage["customer_id"].isin(customers["Customer_Id"])].copy()

In [182]:
usage[ ~usage["customer_id"].isin(customers["Customer_Id"])]

Empty DataFrame
Columns: [usage_id, customer_id, event_date, feature_name, login_count, session_minutes]
Index: []

In [183]:
usage['feature_name']=usage['feature_name'].fillna("Unknown")

In [184]:
usage['feature_name'].value_counts()

feature_name
team_invite       4419
dashboard_view    4415
export_csv        4350
billing_edit      4343
api_post          4304
Unknown            871
Name: count, dtype: int64

In [185]:
usage['feature_name']=usage['feature_name'].str.title()

In [186]:
usage['feature_name'].sample(5)

8111       Billing_Edit
16293    Dashboard_View
10803        Export_Csv
2646         Export_Csv
15757      Billing_Edit
Name: feature_name, dtype: object

In [187]:
usage['login_count']=usage['login_count'].abs()

In [188]:
usage.sample(10)

,usage_id,customer_id,event_date,feature_name,login_count,session_minutes
19126,USG_719127,CUST_2768,2025-04-12,Team_Invite,4,115.74
13022,USG_713023,CUST_2522,2025-08-08,Billing_Edit,6,42.57
11480,USG_711481,CUST_2460,2025-02-25,Export_Csv,5,82.05
16951,USG_716952,CUST_2680,2025-02-16,Export_Csv,2,51.29
17417,USG_717418,CUST_2700,2025-06-29,Billing_Edit,4,35.74
4552,USG_704553,CUST_2185,2025-07-21,Unknown,4,64.55
15025,USG_715026,CUST_2602,2025-10-21,Export_Csv,3,9.00
6095,USG_706096,CUST_2245,2025-03-14,Team_Invite,4,15.59
19726,USG_719727,CUST_2794,2025-02-06,Team_Invite,3,8.82
16688,USG_716689,CUST_2671,2025-07-31,Export_Csv,2,68.64

In [189]:
usage.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22702 entries, 0 to 24755
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   usage_id         22702 non-null  object
 1   customer_id      22702 non-null  object
 2   event_date       22702 non-null  object
 3   feature_name     22702 non-null  object
 4   login_count      22702 non-null  int64
 5   session_minutes  22702 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.2+ MB

In [190]:
usage['event_date']=pd.to_datetime(usage['event_date'],errors='coerce')

In [191]:
usage.columns=usage.columns.str.title()

In [192]:
usage.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22702 entries, 0 to 24755
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Usage_Id         22702 non-null  object
 1   Customer_Id      22702 non-null  object
 2   Event_Date       22702 non-null  datetime64[ns]
 3   Feature_Name     22702 non-null  object
 4   Login_Count      22702 non-null  int64
 5   Session_Minutes  22702 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 1.2+ MB

In [193]:
usage.sample(5)

,Usage_Id,Customer_Id,Event_Date,Feature_Name,Login_Count,Session_Minutes
23675,USG_723676,CUST_2954,2025-12-15,Team_Invite,4,19.53
7453,USG_707454,CUST_2303,2025-03-21,Export_Csv,8,109.97
8257,USG_708258,CUST_2333,2025-07-21,Team_Invite,5,16.35
2920,USG_702921,CUST_2118,2025-07-28,Team_Invite,1,6.66
21058,USG_721059,CUST_2846,2025-03-17,Export_Csv,7,71.53

In [194]:
usage_clean=usage.copy()

In [195]:
usage_clean.to_csv('usage_clean.csv',index=False)

In [196]:
usage_clean

,Usage_Id,Customer_Id,Event_Date,Feature_Name,Login_Count,Session_Minutes
0,USG_700001,CUST_2000,2025-09-08,Dashboard_View,8,114.76
1,USG_700002,CUST_2000,2025-05-11,Export_Csv,3,44.68
2,USG_700003,CUST_2000,2025-01-17,Export_Csv,3,76.59
3,USG_700004,CUST_2000,2025-03-10,Export_Csv,8,58.81
4,USG_700005,CUST_2000,2025-05-25,Export_Csv,3,35.41
...,...,...,...,...,...,...
24751,USG_724752,CUST_2999,2025-01-20,Team_Invite,1,70.09
24752,USG_724753,CUST_2999,2025-01-14,Export_Csv,5,73.85
24753,USG_724754,CUST_2999,2025-05-20,Team_Invite,5,31.07
24754,USG_724755,CUST_2999,2025-10-25,Export_Csv,8,25.97
24755,USG_724756,CUST_2999,2025-01-10,Billing_Edit,3,95.06

# 6. Support Dataset

## Data Inspection

In [197]:
support

,ticket_id,customer_id,ticket_date,priority,category,resolution_time,status
0,TCK_900001,CUST_2006,2025-02-17,HIGH,Login Issue,12,Closed
1,TCK_900002,CUST_2006,2025-07-17,LOW,API Down,41,resolved
2,TCK_900003,CUST_2007,2025-08-23,LOW,Login Issue,21,Closed
3,TCK_900004,CUST_2008,2025-11-10,MEDIUM,Login Issue,43,resolved
4,TCK_900005,CUST_2008,2025-07-22,MEDIUM,Feature Request,1,resolved
...,...,...,...,...,...,...,...
779,TCK_900780,CUST_3491,2025-07-02,MEDIUM,Feature Request,8,resolved
780,TCK_900781,CUST_3491,2025-03-02,HIGH,API Down,19,open
781,TCK_900782,CUST_3496,2025-04-09,MEDIUM,Feature Request,64,resolved
782,TCK_900783,CUST_3496,2025-08-07,LOW,Login Issue,60,Closed
783,TCK_900784,CUST_3496,2025-07-08,CRITICAL,API Down,65,resolved

In [198]:
support.shape

(784, 7)

In [199]:
support.columns

Index(['ticket_id', 'customer_id', 'ticket_date', 'priority', 'category',
       'resolution_time', 'status'],
      dtype='object')

In [200]:
support.dtypes

ticket_id          object
customer_id        object
ticket_date        object
priority           object
category           object
resolution_time     int64
status             object
dtype: object

In [201]:
support.head()

,ticket_id,customer_id,ticket_date,priority,category,resolution_time,status
0,TCK_900001,CUST_2006,2025-02-17,HIGH,Login Issue,12,Closed
1,TCK_900002,CUST_2006,2025-07-17,LOW,API Down,41,resolved
2,TCK_900003,CUST_2007,2025-08-23,LOW,Login Issue,21,Closed
3,TCK_900004,CUST_2008,2025-11-10,MEDIUM,Login Issue,43,resolved
4,TCK_900005,CUST_2008,2025-07-22,MEDIUM,Feature Request,1,resolved

In [202]:
support.tail()

,ticket_id,customer_id,ticket_date,priority,category,resolution_time,status
779,TCK_900780,CUST_3491,2025-07-02,MEDIUM,Feature Request,8,resolved
780,TCK_900781,CUST_3491,2025-03-02,HIGH,API Down,19,open
781,TCK_900782,CUST_3496,2025-04-09,MEDIUM,Feature Request,64,resolved
782,TCK_900783,CUST_3496,2025-08-07,LOW,Login Issue,60,Closed
783,TCK_900784,CUST_3496,2025-07-08,CRITICAL,API Down,65,resolved

In [203]:
support.sample(5)

,ticket_id,customer_id,ticket_date,priority,category,resolution_time,status
495,TCK_900496,CUST_2950,2025-07-09,LOW,Login Issue,54,open
447,TCK_900448,CUST_2838,2025-03-08,MEDIUM,API Down,26,resolved
360,TCK_900361,CUST_2670,2025-05-04,HIGH,API Down,26,open
226,TCK_900227,CUST_2450,2025-09-27,MEDIUM,API Down,41,resolved
143,TCK_900144,CUST_2293,2025-11-25,LOW,Feature Request,31,Closed

In [204]:
support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 784 entries, 0 to 783
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ticket_id        784 non-null    object
 1   customer_id      784 non-null    object
 2   ticket_date      784 non-null    object
 3   priority         784 non-null    object
 4   category         784 non-null    object
 5   resolution_time  784 non-null    int64
 6   status           784 non-null    object
dtypes: int64(1), object(6)
memory usage: 43.0+ KB

In [205]:
support.describe(include='all')

,ticket_id,customer_id,ticket_date,priority,category,resolution_time,status
count,784,784,784,784,784,784.000000,784
unique,784,379,294,4,4,NaN,3
top,TCK_900784,CUST_2136,2025-02-23,HIGH,API Down,NaN,Closed
freq,1,3,11,206,214,NaN,270
mean,NaN,NaN,NaN,NaN,NaN,36.206633,NaN
std,NaN,NaN,NaN,NaN,NaN,19.962050,NaN
min,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,20.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,36.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,52.250000,NaN
max,NaN,NaN,NaN,NaN,NaN,72.000000,NaN

## Data Quality

In [206]:
support.isnull().sum()

ticket_id          0
customer_id        0
ticket_date        0
priority           0
category           0
resolution_time    0
status             0
dtype: int64

In [207]:
support.duplicated().sum()

np.int64(0)

In [208]:
support['ticket_id'].isnull().sum()

np.int64(0)

In [209]:
support['ticket_id'].duplicated().sum()

np.int64(0)

In [210]:
support[ ~support["customer_id"].isin(customers["Customer_Id"])]

,ticket_id,customer_id,ticket_date,priority,category,resolution_time,status
13,TCK_900014,CUST_2043,2025-05-13,LOW,API Down,71,Closed
14,TCK_900015,CUST_2043,2025-06-07,LOW,API Down,39,Closed
48,TCK_900049,CUST_2142,2025-11-25,CRITICAL,Billing Bug,60,open
49,TCK_900050,CUST_2142,2025-02-03,MEDIUM,Feature Request,69,open
50,TCK_900051,CUST_2142,2025-07-16,HIGH,Login Issue,59,open
67,TCK_900068,CUST_2181,2025-04-06,CRITICAL,Login Issue,26,resolved
68,TCK_900069,CUST_2181,2025-08-22,LOW,Login Issue,7,open
69,TCK_900070,CUST_2181,2025-11-27,CRITICAL,Billing Bug,31,Closed
127,TCK_900128,CUST_2274,2025-06-26,HIGH,Feature Request,69,open
128,TCK_900129,CUST_2274,2025-10-25,HIGH,Login Issue,29,open
174,TCK_900175,CUST_2350,2025-05-31,MEDIUM,Feature Request,22,Closed
175,TCK_900176,CUST_2350,2025-07-02,MEDIUM,Login Issue,42,Closed
176,TCK_900177,CUST_2350,2025-08-08,HIGH,API Down,8,open
178,TCK_900179,CUST_2355,2025-02-23,HIGH,Login Issue,16,Closed
179,TCK_900180,CUST_2355,2025-11-09,MEDIUM,Billing Bug,39,resolved
183,TCK_900184,CUST_2361,2025-08-02,MEDIUM,Feature Request,42,Closed
184,TCK_900185,CUST_2361,2025-10-19,LOW,Login Issue,57,resolved
237,TCK_900238,CUST_2471,2025-03-15,CRITICAL,Billing Bug,43,Closed
238,TCK_900239,CUST_2471,2025-06-16,HIGH,API Down,6,open
240,TCK_900241,CUST_2475,2025-08-16,MEDIUM,Login Issue,20,resolved
241,TCK_900242,CUST_2475,2025-09-22,MEDIUM,Billing Bug,7,resolved
256,TCK_900257,CUST_2493,2025-11-16,LOW,Login Issue,63,open
263,TCK_900264,CUST_2511,2025-08-08,MEDIUM,Feature Request,38,Closed
269,TCK_900270,CUST_2520,2025-05-14,CRITICAL,Login Issue,28,resolved
292,TCK_900293,CUST_2551,2025-11-09,MEDIUM,Billing Bug,16,open
293,TCK_900294,CUST_2551,2025-07-22,MEDIUM,API Down,36,Closed
303,TCK_900304,CUST_2572,2025-03-22,MEDIUM,Login Issue,70,Closed
345,TCK_900346,CUST_2650,2025-05-28,MEDIUM,API Down,35,open
346,TCK_900347,CUST_2650,2025-06-12,LOW,API Down,14,resolved
398,TCK_900399,CUST_2746,2025-11-15,CRITICAL,Feature Request,15,open
399,TCK_900400,CUST_2746,2025-08-07,HIGH,Billing Bug,25,resolved
407,TCK_900408,CUST_2772,2025-02-18,CRITICAL,API Down,31,resolved
414,TCK_900415,CUST_2782,2025-06-28,MEDIUM,Billing Bug,25,open
415,TCK_900416,CUST_2782,2025-07-04,MEDIUM,API Down,32,open
430,TCK_900431,CUST_2797,2025-09-29,LOW,Feature Request,8,open
431,TCK_900432,CUST_2797,2025-05-21,CRITICAL,Billing Bug,33,resolved
449,TCK_900450,CUST_2842,2025-03-11,HIGH,Billing Bug,40,resolved
450,TCK_900451,CUST_2842,2025-08-28,CRITICAL,API Down,3,Closed
451,TCK_900452,CUST_2842,2025-10-01,HIGH,Feature Request,34,open
455,TCK_900456,CUST_2857,2025-09-01,MEDIUM,API Down,60,resolved
456,TCK_900457,CUST_2857,2025-03-08,LOW,Billing Bug,32,Closed
462,TCK_900463,CUST_2867,2025-07-29,LOW,Feature Request,28,Closed
471,TCK_900472,CUST_2883,2025-05-25,LOW,Billing Bug,5,open
531,TCK_900532,CUST_3018,2025-09-27,HIGH,Login Issue,14,resolved
532,TCK_900533,CUST_3018,2025-09-29,MEDIUM,API Down,46,Closed
533,TCK_900534,CUST_3020,2025-06-10,HIGH,API Down,44,open
534,TCK_900535,CUST_3020,2025-02-25,LOW,API Down,46,Closed
535,TCK_900536,CUST_3020,2025-06-03,CRITICAL,Feature Request,64,resolved
574,TCK_900575,CUST_3082,2025-11-15,HIGH,Billing Bug,26,Closed
575,TCK_900576,CUST_3082,2025-06-16,LOW,Billing Bug,21,open
576,TCK_900577,CUST_3082,2025-03-08,CRITICAL,Billing Bug,18,open
577,TCK_900578,CUST_3084,2025-03-21,MEDIUM,Feature Request,22,resolved
591,TCK_900592,CUST_3107,2025-04-05,LOW,Feature Request,27,Closed
592,TCK_900593,CUST_3107,2025-03-08,HIGH,Login Issue,20,open
593,TCK_900594,CUST_3107,2025-04-27,HIGH,Billing Bug,21,Closed
612,TCK_900613,CUST_3163,2025-05-06,HIGH,API Down,40,Closed
613,TCK_900614,CUST_3163,2025-12-16,CRITICAL,Billing Bug,58,resolved
614,TCK_900615,CUST_3163,2025-09-17,CRITICAL,Feature Request,39,Closed
627,TCK_900628,CUST_3180,2025-02-15,MEDIUM,Billing Bug,5,open
628,TCK_900629,CUST_3180,2025-10-10,CRITICAL,Login Issue,30,Closed
629,TCK_900630,CUST_3180,2025-02-16,CRITICAL,Login Issue,57,resolved
677,TCK_900678,CUST_3262,2025-06-23,MEDIUM,Billing Bug,8,open
678,TCK_900679,CUST_3262,2025-03-08,MEDIUM,Login Issue,45,resolved
679,TCK_900680,CUST_3270,2025-03-01,LOW,Login Issue,4,Closed
680,TCK_900681,CUST_3270,2025-09-22,LOW,Billing Bug,38,Closed
681,TCK_900682,CUST_3270,2025-09-12,LOW,API Down,62,open
737,TCK_900738,CUST_3373,2025-07-12,CRITICAL,Feature Request,70,open
738,TCK_900739,CUST_3373,2025-07-05,MEDIUM,Billing Bug,2,resolved

In [211]:
len(support[ ~support["customer_id"].isin(customers["Customer_Id"])])

68

In [212]:
support['customer_id'].isnull().sum()

np.int64(0)

In [213]:
support['priority'].unique()

array(['HIGH', 'LOW', 'MEDIUM', 'CRITICAL'], dtype=object)

In [214]:
support['priority'].value_counts(dropna=False)

priority
HIGH        206
LOW         199
CRITICAL    194
MEDIUM      185
Name: count, dtype: int64

In [215]:
support['category'].unique()

array(['Login Issue', 'API Down', 'Feature Request', 'Billing Bug'],
      dtype=object)

In [216]:
support['category'].value_counts()

category
API Down           214
Billing Bug        197
Login Issue        192
Feature Request    181
Name: count, dtype: int64

In [217]:
support['status'].unique()

array(['Closed', 'resolved', 'open'], dtype=object)

In [218]:
support['status'].value_counts(dropna=False)

status
Closed      270
resolved    261
open        253
Name: count, dtype: int64

In [219]:
support[support['resolution_time']<0]

Empty DataFrame
Columns: [ticket_id, customer_id, ticket_date, priority, category, resolution_time, status]
Index: []

In [220]:
(support['resolution_time']<0).sum()

np.int64(0)

## Data Cleaning

In [221]:
support = support[support["customer_id"].isin(customers["Customer_Id"])].copy()

In [222]:
support[~support['customer_id'].isin(customers['Customer_Id'])]

Empty DataFrame
Columns: [ticket_id, customer_id, ticket_date, priority, category, resolution_time, status]
Index: []

In [223]:
support['ticket_date']=pd.to_datetime(support['ticket_date'],errors='coerce')

In [224]:
support.info()

<class 'pandas.core.frame.DataFrame'>
Index: 716 entries, 0 to 783
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ticket_id        716 non-null    object
 1   customer_id      716 non-null    object
 2   ticket_date      716 non-null    datetime64[ns]
 3   priority         716 non-null    object
 4   category         716 non-null    object
 5   resolution_time  716 non-null    int64
 6   status           716 non-null    object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 44.8+ KB

In [225]:
support['ticket_date'].min()

Timestamp('2025-01-31 00:00:00')

In [226]:
support['ticket_date'].max()

Timestamp('2025-12-17 00:00:00')

In [227]:
support['priority']=support['priority'].str.title()

In [228]:
support['priority'].value_counts()

priority
High        191
Low         183
Critical    178
Medium      164
Name: count, dtype: int64

In [229]:
support['status']=support['status'].str.title()

In [230]:
support['status'].value_counts()

status
Closed      246
Resolved    242
Open        228
Name: count, dtype: int64

In [231]:
support.columns=support.columns.str.title()

In [232]:
support

,Ticket_Id,Customer_Id,Ticket_Date,Priority,Category,Resolution_Time,Status
0,TCK_900001,CUST_2006,2025-02-17,High,Login Issue,12,Closed
1,TCK_900002,CUST_2006,2025-07-17,Low,API Down,41,Resolved
2,TCK_900003,CUST_2007,2025-08-23,Low,Login Issue,21,Closed
3,TCK_900004,CUST_2008,2025-11-10,Medium,Login Issue,43,Resolved
4,TCK_900005,CUST_2008,2025-07-22,Medium,Feature Request,1,Resolved
...,...,...,...,...,...,...,...
779,TCK_900780,CUST_3491,2025-07-02,Medium,Feature Request,8,Resolved
780,TCK_900781,CUST_3491,2025-03-02,High,API Down,19,Open
781,TCK_900782,CUST_3496,2025-04-09,Medium,Feature Request,64,Resolved
782,TCK_900783,CUST_3496,2025-08-07,Low,Login Issue,60,Closed
783,TCK_900784,CUST_3496,2025-07-08,Critical,API Down,65,Resolved

In [233]:
support_clean=support.copy()

In [234]:
support_clean

,Ticket_Id,Customer_Id,Ticket_Date,Priority,Category,Resolution_Time,Status
0,TCK_900001,CUST_2006,2025-02-17,High,Login Issue,12,Closed
1,TCK_900002,CUST_2006,2025-07-17,Low,API Down,41,Resolved
2,TCK_900003,CUST_2007,2025-08-23,Low,Login Issue,21,Closed
3,TCK_900004,CUST_2008,2025-11-10,Medium,Login Issue,43,Resolved
4,TCK_900005,CUST_2008,2025-07-22,Medium,Feature Request,1,Resolved
...,...,...,...,...,...,...,...
779,TCK_900780,CUST_3491,2025-07-02,Medium,Feature Request,8,Resolved
780,TCK_900781,CUST_3491,2025-03-02,High,API Down,19,Open
781,TCK_900782,CUST_3496,2025-04-09,Medium,Feature Request,64,Resolved
782,TCK_900783,CUST_3496,2025-08-07,Low,Login Issue,60,Closed
783,TCK_900784,CUST_3496,2025-07-08,Critical,API Down,65,Resolved

support_clean=support.copy()

In [235]:
support_clean

,Ticket_Id,Customer_Id,Ticket_Date,Priority,Category,Resolution_Time,Status
0,TCK_900001,CUST_2006,2025-02-17,High,Login Issue,12,Closed
1,TCK_900002,CUST_2006,2025-07-17,Low,API Down,41,Resolved
2,TCK_900003,CUST_2007,2025-08-23,Low,Login Issue,21,Closed
3,TCK_900004,CUST_2008,2025-11-10,Medium,Login Issue,43,Resolved
4,TCK_900005,CUST_2008,2025-07-22,Medium,Feature Request,1,Resolved
...,...,...,...,...,...,...,...
779,TCK_900780,CUST_3491,2025-07-02,Medium,Feature Request,8,Resolved
780,TCK_900781,CUST_3491,2025-03-02,High,API Down,19,Open
781,TCK_900782,CUST_3496,2025-04-09,Medium,Feature Request,64,Resolved
782,TCK_900783,CUST_3496,2025-08-07,Low,Login Issue,60,Closed
783,TCK_900784,CUST_3496,2025-07-08,Critical,API Down,65,Resolved

In [236]:
support_clean.to_csv('support_clean.csv',index=False)

# Conclusion
The datasets have been successfully cleaned and validated. Data quality issues such as missing values, duplicate records, inconsistent values, incorrect data types, and relationship mismatches were resolved.

These cleaned datasets are now ready for exploratory data analysis, SQL-based business analysis, and dashboard development.